<?php
array(
    'data' =>
    array(
        0 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/84',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/84/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/84/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '84',
            'attributes' =>
            array(
                'jobId' => 84,
                'parentJobId' => 0,
                'activeProcessId' => 91055,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:47.000Z',
                'endTime' => '2019-12-31T17:56:47.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:47.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:47.482Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:00',
            ),
        ),
        1 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/83',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/83/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/83/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '83',
            'attributes' =>
            array(
                'jobId' => 83,
                'parentJobId' => 0,
                'activeProcessId' => 95414,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:46.000Z',
                'endTime' => '2019-12-31T17:56:47.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:46.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:47.162Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:01',
            ),
        ),
        2 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/82',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/82/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/82/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '82',
            'attributes' =>
            array(
                'jobId' => 82,
                'parentJobId' => 0,
                'activeProcessId' => 91055,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:46.000Z',
                'endTime' => '2019-12-31T17:56:46.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:46.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:46.741Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:00',
            ),
        ),
        3 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/80',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/80/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/80/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '80',
            'attributes' =>
            array(
                'jobId' => 80,
                'parentJobId' => 0,
                'activeProcessId' => 95414,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:30.000Z',
                'endTime' => '2019-12-31T17:56:31.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:30.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:31.015Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:01',
            ),
        ),
        4 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/79',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/79/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/79/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '79',
            'attributes' =>
            array(
                'jobId' => 79,
                'parentJobId' => 0,
                'activeProcessId' => 91055,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:30.000Z',
                'endTime' => '2019-12-31T17:56:30.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:30.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:30.675Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:00',
            ),
        ),
        5 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/81',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/81/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/81/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '81',
            'attributes' =>
            array(
                'jobId' => 81,
                'parentJobId' => 0,
                'activeProcessId' => 91055,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:30.000Z',
                'endTime' => '2019-12-31T17:56:31.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:30.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:31.309Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:01',
            ),
        ),
        6 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/77',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/77/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/77/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '77',
            'attributes' =>
            array(
                'jobId' => 77,
                'parentJobId' => 0,
                'activeProcessId' => 91055,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:29.000Z',
                'endTime' => '2019-12-31T17:56:29.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:29.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:29.897Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:00',
            ),
        ),
        7 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/78',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/78/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/78/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '78',
            'attributes' =>
            array(
                'jobId' => 78,
                'parentJobId' => 0,
                'activeProcessId' => 95414,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:29.000Z',
                'endTime' => '2019-12-31T17:56:30.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:29.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:30.315Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:01',
            ),
        ),
        8 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/76',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/76/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/76/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '76',
            'attributes' =>
            array(
                'jobId' => 76,
                'parentJobId' => 0,
                'activeProcessId' => 95414,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:29.000Z',
                'endTime' => '2019-12-31T17:56:29.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:29.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:29.516Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:00',
            ),
        ),
        9 =>
        array(
            'links' =>
            array(
                'self' =>
                array(
                    'href' => '/admin/jobs/75',
                ),
                'file-lists' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/75/file-lists',
                ),
                'try-logs' =>
                array(
                    'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs/75/try-logs',
                ),
            ),
            'type' => 'job',
            'id' => '75',
            'attributes' =>
            array(
                'jobId' => 75,
                'parentJobId' => 0,
                'activeProcessId' => 91055,
                'jobType' => 'IMAGEDELETE',
                'policyName' => '',
                'scheduleName' => '',
                'clientName' => '',
                'controlHost' => '',
                'jobOwner' => 'root',
                'jobGroup' => '',
                'backupId' => '',
                'sourceMediaId' => '',
                'sourceStorageUnitName' => '',
                'sourceMediaServerName' => '',
                'destinationMediaId' => '',
                'destinationStorageUnitName' => '',
                'destinationMediaServerName' => '',
                'streamNumber' => 0,
                'copyNumber' => 0,
                'priority' => 0,
                'compression' => 0,
                'status' => 0,
                'state' => 'DONE',
                'numberOfFiles' => 0,
                'estimatedFiles' => 0,
                'kilobytesTransferred' => 0,
                'kilobytesToTransfer' => 0,
                'transferRate' => 0,
                'percentComplete' => 100,
                'restartable' => 0,
                'suspendable' => 0,
                'resumable' => 0,
                'frozenImage' => 0,
                'transportType' => 'LAN',
                'currentOperation' => 0,
                'robotName' => '',
                'vaultName' => '',
                'profileName' => '',
                'sessionId' => 0,
                'numberOfTapeToEject' => 0,
                'submissionType' => 0,
                'dumpHost' => '',
                'instanceDatabaseName' => '',
                'auditUserName' => '',
                'auditDomainName' => '',
                'auditDomainType' => 0,
                'restoreBackupIDs' => '',
                'startTime' => '2019-12-31T17:56:28.000Z',
                'endTime' => '2019-12-31T17:56:29.000Z',
                'activeTryStartTime' => '2019-12-31T17:56:28.000Z',
                'lastUpdateTime' => '2019-12-31T17:56:29.094Z',
                'initiatorId' => '',
                'try' => 1,
                'cancellable' => 1,
                'jobQueueReason' => -99,
                'jobQueueResource' => '',
                'kilobytesDataTransferred' => 0,
                'elapsedTime' => '00:00:01',
            ),
        ),
    ),
    'meta' =>
    array(
        'pagination' =>
        array(
            'next' => 10,
            'pages' => 2,
            'offset' => 0,
            'last' => 10,
            'limit' => 10,
            'count' => 15,
            'page' => 0,
            'first' => 0,
        ),
    ),
    'links' =>
    array(
        'next' =>
        array(
            'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs?page%5Boffset%5D=10&page%5Blimit%5D=10&sort=-startTime',
        ),
        'self' =>
        array(
            'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs?page%5Boffset%5D=0&page%5Blimit%5D=10&sort=-startTime',
        ),
        'last' =>
        array(
            'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs?page%5Boffset%5D=10&page%5Blimit%5D=10&sort=-startTime',
        ),
        'first' =>
        array(
            'href' => 'https://192.168.0.105:1556/netbackup/admin/jobs?page%5Boffset%5D=0&page%5Blimit%5D=10&sort=-startTime',
        ),
    ),
);
